    <header class="site-header">
        <div class="contenedor contenido-header">
            <div class="barra">
                <a href="#">
                    <img src="../img/logo.jpg" width="160" alt="Logotipo de Bienes Raices">
                </a>
                <div class="mobile-menu">
                    <a href="#navegacion">
                        <img src="../img/barras.svg" alt="Icono Menu">
                    </a>
                </div>

                <nav id="navegacion" class="navegacion">
                    <a href="agenda.php">Agenda</a>
                    <a href="citas.php">Citas</a>   
                    <a href="clientes.php">Clientes</a>
                    <a href="registrarCliente.php">Registrar Cliente</a>
                    <a href="crearcita.php">Crear Cita</a>
                    <a href="duenios.php">Dueños</a>
                    <a href="casas.php">Casas</a>
                    <a href="registrarCasa.php">Registrar Casa</a>
                    <a href="vendedores.php">Vendedores</a>
                    <a href="ventas.php">Ventas</a>
                </nav>
				
            </div>
		<a href="salir.php" style='border:1px solid #fff;color:#fff;width:160px;margin:left;text-align:center;'>Cerrar sesion</a>	
        </div> 
		
    </header>