    <header class="site-header">
        <div class="contenedor contenido-header">
            <div class="barra">
                <a href="#">
                    <img src="../img/logo.jpg" width="160" alt="Logotipo de Bienes Raices">
                </a>
                <div class="mobile-menu">
                    <a href="#navegacion">
                        <img src="../img/barras.svg" alt="Icono Menu">
                    </a>
                </div>

                <nav id="navegacion" class="navegacion">
                    
                    <a href="miscitas.php">Mis Citas</a>
                    <a href="publicaciones.php">Publicaciones</a>
                    <a href="salir.php">Cerrar Sesión</a>
                    
                </nav>
				
            </div>
		<a href="salir.php" style='border:1px solid #fff;color:#fff;width:160px;margin:left;text-align:center;'>Cerrar sesion</a>	
        </div> 
		
    </header>