    <footer class="site-footer seccion">
        <div class="contenedor contenedor-footer">
            <nav class="navegacion">
                <a href="nosotros.php">Nosotros</a>
                <a href="publicaciones.php">Publicaciones</a>
                <a href="contacto.php">Contacto</a>
                <a href="iniciarsesion.php">Iniciar Sesión</a>
            </nav>
            <p class="copyright">Todos los Derechos Reservados 2019 &copy; </p>
        </div>
    </footer>