    <header class="site-header">
        <div class="contenedor contenido-header">
            <div class="barra">
                <a href="index.php">
                    <img src="img/logo.jpg" width="160" alt="Logotipo de Bienes Raices">
                </a>
                <div class="mobile-menu">
                    <a href="#navegacion">
                        <img src="img/barras.svg" alt="Icono Menu">
                    </a>
                </div>

                <nav id="navegacion" class="navegacion">
                    <a href="nosotros.php">Nosotros</a>
                    <a href="publicaciones.php">Publicaciones</a>   
                    <a href="contacto.php">Contacto</a>
                    <a href="iniciarsesion.php">Iniciar Sesión</a>
                </nav>
            </div>
        </div> 
    </header>